name: "Feature Request"
description: "Request a feature or enhancement"
labels: ["enhancement"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thank you for creating an feature request 😎!

        Please search open/closed feature requests before submitting. Someone might have asked the same thing before 😎!

          - [Issues](https://github.com/hirotomoyamada/ai-commit/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
          - [Closed Issues](https://github.com/hirotomoyamada/ai-commit/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe your feature request in one or two sentences."
    validations:
      required: true
  - type: "textarea"
    id: "justification"
    attributes:
      label: "Problem Statement/Justification"
      description: |
        Provide valid reasons why this feature should be added to AI Commit.

        If this feature is related to a problem you've encountered, please describe it as well.
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "Proposed Solution or Command"
      description: |
        Provide code snippets, gists, or links to the ideal design or command.
      placeholder: |
        As a user, I expected ___ behavior, but observed ___ instead.

        Ideal steps I would like to see:
        1. Execute the command '...'
        2. Observe the following output '...'
        3. ....
  - type: "textarea"
    id: "alternatives"
    attributes:
      label: "Alternatives"
      description: |
        Have you considered any alternative solutions or features before making this request?
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |
        Do you have any resources (links, screenshots, etc.) that could assist in understanding or implementing this feature?
